<?php

namespace Modules\Installer\Database\Seeders\Attribute;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeTableSeeder extends Seeder
{
     /**
     * Seed the application's database.
     *
     * @param  array  $parameters
     * @return void
     */
    public function run($parameters = [])
    {
        DB::table('attributes')->delete();

        DB::table('attribute_translations')->delete();

        $now = Carbon::now();

        $defaultLocale = $parameters['default_locale'] ?? config('app.locale');

        DB::table('attributes')->insert([
            [
                'id'                  => 1,
                'code'                => 'sku',
                'admin_name'          => "sku",
                'type'                => 'text',
                'validation'          => null,
                'position'            => 1,
                'is_required'         => 1,
                'is_unique'           => 1,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 2,
                'code'                => 'name',
                'admin_name'          => "name",
                'type'                => 'text',
                'validation'          => null,
                'position'            => 3,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 1,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 3,
                'code'                => 'url_key',
                'admin_name'          => 'url-key',
                'type'                => 'text',
                'validation'          => null,
                'position'            => 4,
                'is_required'         => 1,
                'is_unique'           => 1,
                'value_per_locale'    => 1,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 4,
                'code'                => 'tax_category_id',
                'admin_name'          => 'tax-category',
                'type'                => 'select',
                'validation'          => null,
                'position'            => 5,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 5,
                'code'                => 'new',
                'admin_name'          => 'new',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 6,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 6,
                'code'                => 'featured',
                'admin_name'          => 'featured',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 7,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 7,
                'code'                => 'visible_individually',
                'admin_name'          => 'visible-individually',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 9,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 8,
                'code'                => 'status',
                'admin_name'          => 'status',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 10,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 9,
                'code'                => 'short_description',
                'admin_name'          => 'short-description',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => 11,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 1,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 10,
                'code'                => 'description',
                'admin_name'          => 'description',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => 12,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 1,
                'enable_wysiwyg'      => 1,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 11,
                'code'                => 'price',
                'admin_name'          => 'price',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => 13,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 1,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 1,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 12,
                'code'                => 'cost',
                'admin_name'          => 'cost',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => 14,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 13,
                'code'                => 'special_price',
                'admin_name'          => 'special-price',
                'type'                => 'price',
                'validation'          => 'decimal',
                'position'            => 15,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 14,
                'code'                => 'special_price_from',
                'admin_name'          => 'special-price-from',
                'type'                => 'date',
                'validation'          => null,
                'position'            => 16,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 15,
                'code'                => 'special_price_to',
                'admin_name'          => 'special-price-to',
                'type'                => 'date',
                'validation'          => null,
                'position'            => 17,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 1,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 16,
                'code'                => 'meta_title',
                'admin_name'          => 'meta-title',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => 18,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 17,
                'code'                => 'meta_keywords',
                'admin_name'          => 'meta-keywords',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => 20,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 18,
                'code'                => 'meta_description',
                'admin_name'          => 'meta-description',
                'type'                => 'textarea',
                'validation'          => null,
                'position'            => 21,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 1,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 19,
                'code'                => 'length',
                'admin_name'          => 'length',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => 22,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 20,
                'code'                => 'width',
                'admin_name'          => 'width',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => 23,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 21,
                'code'                => 'height',
                'admin_name'          => 'height',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => 24,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 22,
                'code'                => 'weight',
                'admin_name'          => 'weight',
                'type'                => 'text',
                'validation'          => 'decimal',
                'position'            => 25,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 23,
                'code'                => 'color',
                'admin_name'          => 'color',
                'type'                => 'select',
                'validation'          => null,
                'position'            => 26,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 1,
                'is_configurable'     => 1,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 24,
                'code'                => 'size',
                'admin_name'          => 'size',
                'type'                => 'select',
                'validation'          => null,
                'position'            => 27,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 1,
                'is_configurable'     => 1,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 25,
                'code'                => 'brand',
                'admin_name'          => 'brand',
                'type'                => 'select',
                'validation'          => null,
                'position'            => 28,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 1,
                'is_configurable'     => 0,
                'is_user_defined'     => 1,
                'is_visible_on_front' => 1,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 26,
                'code'                => 'guest_checkout',
                'admin_name'          => 'guest-checkout',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 8,
                'is_required'         => 1,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 27,
                'code'                => 'product_number',
                'admin_name'          => 'product-number',
                'type'                => 'text',
                'validation'          => null,
                'position'            => 2,
                'is_required'         => 0,
                'is_unique'           => 1,
                'value_per_locale'    => 0,
                'value_per_channel'   => 0,
                'default_value'       => null,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ], [
                'id'                  => 28,
                'code'                => 'manage_stock',
                'admin_name'          => 'manage-stock',
                'type'                => 'boolean',
                'validation'          => null,
                'position'            => 1,
                'is_required'         => 0,
                'is_unique'           => 0,
                'value_per_locale'    => 0,
                'value_per_channel'   => 1,
                'default_value'       => 1,
                'is_filterable'       => 0,
                'is_configurable'     => 0,
                'is_user_defined'     => 0,
                'is_visible_on_front' => 0,
                'is_comparable'       => 0,
                'enable_wysiwyg'      => 0,
                'created_at'          => $now,
                'updated_at'          => $now,
            ],
        ]);

        $locales = $parameters['allowed_locales'] ?? [$defaultLocale];

        foreach ($locales as $locale) {
            DB::table('attribute_translations')->insert([
                [
                    'locale'       => $locale,
                    'name'         => 'sku',
                    'attribute_id' => 1,
                ], [
                    'locale'       => $locale,
                    'name'         => 'name',
                    'attribute_id' => 2,
                ], [
                    'locale'       => $locale,
                    'name'         => 'url-key',
                    'attribute_id' => 3,
                ], [
                    'locale'       => $locale,
                    'name'         => 'tax-category',
                    'attribute_id' => 4,
                ], [
                    'locale'       => $locale,
                    'name'         => 'new',
                    'attribute_id' => 5,
                ], [
                    'locale'       => $locale,
                    'name'         => 'featured',
                    'attribute_id' => 6,
                ], [
                    'locale'       => $locale,
                    'name'         => 'visible-individually',
                    'attribute_id' => 7,
                ], [
                    'locale'       => $locale,
                    'name'         => 'status',
                    'attribute_id' => 8,
                ], [
                    'locale'       => $locale,
                    'name'         => 'short-description',
                    'attribute_id' => 9,
                ], [
                    'locale'       => $locale,
                    'name'         => 'description',
                    'attribute_id' => 10,
                ], [
                    'locale'       => $locale,
                    'name'         => 'price',
                    'attribute_id' => 11,
                ], [
                    'locale'       => $locale,
                    'name'         => 'cost',
                    'attribute_id' => 12,
                ], [
                    'locale'       => $locale,
                    'name'         => 'special-price',
                    'attribute_id' => 13,
                ], [
                    'locale'       => $locale,
                    'name'         => 'special-price-from',
                    'attribute_id' => 14,
                ], [
                    'locale'       => $locale,
                    'name'         => 'special-price-to',
                    'attribute_id' => 15,
                ], [
                    'locale'       => $locale,
                    'name'         => 'meta-title',
                    'attribute_id' => 16,
                ], [
                    'locale'       => $locale,
                    'name'         => 'meta-keywords',
                    'attribute_id' => 17,
                ], [
                    'locale'       => $locale,
                    'name'         => 'meta-description',
                    'attribute_id' => 18,
                ], [
                    'locale'       => $locale,
                    'name'         => 'length',
                    'attribute_id' => 19,
                ], [
                    'locale'       => $locale,
                    'name'         => 'width',
                    'attribute_id' => 20,
                ], [
                    'locale'       => $locale,
                    'name'         => 'height',
                    'attribute_id' => 21,
                ], [
                    'locale'       => $locale,
                    'name'         => 'weight',
                    'attribute_id' => 22,
                ], [
                    'locale'       => $locale,
                    'name'         => 'color',
                    'attribute_id' => 23,
                ], [
                    'locale'       => $locale,
                    'name'         => 'size',
                    'attribute_id' => 24,
                ], [
                    'locale'       => $locale,
                    'name'         => 'brand',
                    'attribute_id' => 25,
                ], [
                    'locale'       => $locale,
                    'name'         => 'guest-checkout',
                    'attribute_id' => 26,
                ], [
                    'locale'       => $locale,
                    'name'         => 'product-number',
                    'attribute_id' => 27,
                ], [
                    'locale'       => $locale,
                    'name'         => 'manage-stock',
                    'attribute_id' => 28,
                ],
            ]);
        }
    }
}
